# Go2 PD控制器配置文件
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/yun1w/policy.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/Yun1W/scene_lab.xml"
# Total simulation time
simulation_duration: 500.0
# Simulation time step
simulation_dt: 0.005
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 4

kps: [15, 15, 15, 0, 15, 15, 15, 0, 15, 15, 15, 0, 15, 15, 15, 0]
kds: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]

# default_angles: [0.0,  0.6,  -1.2,  
#                   0.0, 0.6, -1.2, 
#                   0.0,  -0.6,  1.2,  
#                   0.0, -0.6, 1.2]
default_angles: [0.0,  0.6,  -1.2,  0.0,
                  0.0, 0.6, -1.2, 0.0,
                  0.0,  -0.6,  1.2,  0.0,
                  0.0, -0.6, 1.2, 0.0]
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
# action_scale: [0.25, 0.25, 0.25, 0.25,  # FR leg
#                0.25, 0.25, 0.25, 0.25, # FL leg
#                0.25, 0.25, 0.25, 0.25, # RR leg
#                0.25, 0.25, 0.25, 0.25, 
#                ]  # RL leg

action_scale: [0.25, 0.25, 0.25, 10, # FR leg
               0.25, 0.25, 0.25, 10, # FL leg
               0.25, 0.25, 0.25, 10, # RR leg
               0.25, 0.25, 0.25, 10, 
               ]  # RL leg
wheel_indices: [3, 7, 11, 15]
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 16
num_obs: 57

cmd_init: [0.0, 0.0, 0.0]
